### ISSUE TITLE
`useRunningHeader` hook returns stale data after switching the article

### ISSUE THREAD

**Issue by wisnie** [typeofweb/typeofweb.com#167]
There's a text in the navigation which indicates what section of the article we are currently reading. It works if we navigate directly to the article (e.g. permalink). However, when we change the article, instead of indicating our current place in the text, it displays the heading of the last viewed article.

Steps to reproduce:
1. Navigate to an article (e.g. https://typeofweb.com/typescript-infer-i-typy-warunkowe),
2. Use the top level navigation to display a list of articles (e.g. click `JavaScript`),
3. Open different article (e.g. https://typeofweb.com/react-hooks-wlasne-hooki);

**Comment by mmiszy** [comment]
@allcontributors please add @wisnie for bug
