### ISSUE TITLE
Article about the blog

### ISSUE THREAD

**Issue by jcubic** [typeofweb/typeofweb.com#176]
I'm 100% sure but I think that I've seen the article about how you created this blog in Next.js. But I can't find it now. Did you delete it? Or it never existed and it was just [How I Built My Blog](https://www.joshwcomeau.com/blog/how-i-built-my-blog/) that is in my browser history. Without the URL I can't look it up on archive.org.

**Comment by mmiszy** [comment]
https://ohmydev.pl/post/nowe-typeofweb-com-next-js-tailwind-css-markdown-statycznie-i-szybko-53op

**Comment by jcubic** [comment]
Thanks I was searching on the blog.
